// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Samuel_Duran_Ap1_PF.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220411081527_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Entidades.Almacenes", b =>
                {
                    b.Property<int>("AlmacenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DenominacionCentro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCentro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlmacenId");

                    b.ToTable("Almacenes");

                    b.HasData(
                        new
                        {
                            AlmacenId = 1,
                            DenominacionCentro = "Santiago - Edenorte",
                            NombreCentro = "N100"
                        },
                        new
                        {
                            AlmacenId = 2,
                            DenominacionCentro = "Samaná - Edenorte",
                            NombreCentro = "N200"
                        },
                        new
                        {
                            AlmacenId = 3,
                            DenominacionCentro = "San Francisco - Edenorte",
                            NombreCentro = "N300"
                        },
                        new
                        {
                            AlmacenId = 4,
                            DenominacionCentro = "Puerto Plata - Edenorte",
                            NombreCentro = "N400"
                        },
                        new
                        {
                            AlmacenId = 5,
                            DenominacionCentro = "Mao- Edenorte",
                            NombreCentro = "N500"
                        },
                        new
                        {
                            AlmacenId = 6,
                            DenominacionCentro = "La vega - Edenorte",
                            NombreCentro = "N600"
                        },
                        new
                        {
                            AlmacenId = 7,
                            DenominacionCentro = "Espaillat - Edenorte",
                            NombreCentro = "N700"
                        },
                        new
                        {
                            AlmacenId = 8,
                            DenominacionCentro = "Valverde - Edenorte",
                            NombreCentro = "N800"
                        });
                });

            modelBuilder.Entity("Entidades.EntradasAlmacen", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlmacenOrigenAlmacenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportistaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.HasIndex("AlmacenOrigenAlmacenId");

                    b.HasIndex("TransportistaId");

                    b.ToTable("EntradasAlmacenes");
                });

            modelBuilder.Entity("Entidades.Materiales", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadesMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorInventario")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Entidades.MaterialesDespachados", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SalidaId");

                    b.ToTable("MaterialesDespachados");
                });

            modelBuilder.Entity("Entidades.MaterialesRecibidos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("EntradaId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialesRecibidos");
                });

            modelBuilder.Entity("Entidades.SalidasAlmacen", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlmacenDestinoAlmacenId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportistaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalidaId");

                    b.HasIndex("AlmacenDestinoAlmacenId");

                    b.HasIndex("TransportistaId");

                    b.ToTable("SalidasAlmacen");
                });

            modelBuilder.Entity("Entidades.Transportistas", b =>
                {
                    b.Property<int>("TransportistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroCarnet")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransportistaId");

                    b.ToTable("Transportistas");
                });

            modelBuilder.Entity("Entidades.EntradasAlmacen", b =>
                {
                    b.HasOne("Entidades.Almacenes", "AlmacenOrigen")
                        .WithMany()
                        .HasForeignKey("AlmacenOrigenAlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Transportistas", "Transportista")
                        .WithMany()
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlmacenOrigen");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("Entidades.MaterialesDespachados", b =>
                {
                    b.HasOne("Entidades.Materiales", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.SalidasAlmacen", "Salida")
                        .WithMany("MaterialesDespachados")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Entidades.MaterialesRecibidos", b =>
                {
                    b.HasOne("Entidades.EntradasAlmacen", "entrada")
                        .WithMany("MaterialesRecibidos")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Materiales", "material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entrada");

                    b.Navigation("material");
                });

            modelBuilder.Entity("Entidades.SalidasAlmacen", b =>
                {
                    b.HasOne("Entidades.Almacenes", "AlmacenDestino")
                        .WithMany()
                        .HasForeignKey("AlmacenDestinoAlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Transportistas", "Transportista")
                        .WithMany()
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlmacenDestino");

                    b.Navigation("Transportista");
                });

            modelBuilder.Entity("Entidades.EntradasAlmacen", b =>
                {
                    b.Navigation("MaterialesRecibidos");
                });

            modelBuilder.Entity("Entidades.SalidasAlmacen", b =>
                {
                    b.Navigation("MaterialesDespachados");
                });
#pragma warning restore 612, 618
        }
    }
}
